/*  Login */
export const CHECK_ISAUTH = 'CHECK_ISAUTH';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const UPDATE_USER_DETAILS = 'UPDATE_USER_DETAILS';

/*  Header */
export const LOGIN_MODEL_OPEN = 'LOGIN_MODEL_OPEN';
export const SIGNUP_MODEL_OPEN = 'SIGNUP_MODEL_OPEN';
export const IS_CREATE_MODEL_OPEN = 'IS_CREATE_MODEL_OPEN';
export const IS_VIEW_MODEL_OPEN = 'IS_VIEW_MODEL_OPEN';
export const IS_DELETE_MODEL_OPEN = 'IS_DELETE_MODEL_OPEN';

/*  Cars */
export const GET_CAR_LISTING = 'GET_CAR_LISTING';
export const GET_USER_CAR_LISTING = 'GET_USER_CAR_LISTING';
export const GET_CAR_DETAILS = 'GET_CAR_DETAILS';
export const CLEAR_CAR_DETAILS = 'CLEAR_CAR_DETAILS';
